In [114]:
import pandas as pd
import requests 

requisicao = requests.get("https://pt.wikipedia.org/wiki/Campeonato_Brasileiro_de_Futebol_de_2023_-_S%C3%A9rie_A")

tabelas = pd.read_html(requisicao.text)
tabela_classificacao = tabelas[6]
tabela_jogos = tabelas[7]
display(tabela_classificacao)
display(tabela_jogos)

C:\Users\berna\AppData\Local\Temp\ipykernel_17856\2130164979.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabelas = pd.read_html(requisicao.text)

,Pos,Equipevde,Pts,J,V,E,D,GP,GC,SG,Classificação ou descenso
0,1,Palmeiras (T),63,35,18,9,8,58,32,+26,Fase de grupos da Copa Libertadores de 2024
1,2,Flamengo (T),63,35,18,9,8,54,37,+17,Fase de grupos da Copa Libertadores de 2024
2,3,Botafogo (T),62,35,18,8,9,56,33,+23,Fase de grupos da Copa Libertadores de 2024
3,4,Atlético Mineiro (X),60,35,17,9,9,46,27,+19,Fase de grupos da Copa Libertadores de 2024
4,5,Grêmio (X),59,35,18,5,12,57,53,+4,Segunda fase da Copa Libertadores de 2024
5,6,Red Bull Bragantino (X),59,35,16,11,8,46,31,+15,Segunda fase da Copa Libertadores de 2024
6,7,Fluminense (Q),53,35,15,8,12,46,43,+3,Fase de grupos da Copa Libertadores de 2024[a]
7,8,Athletico Paranaense,52,35,13,13,9,47,39,+8,Fase de grupos da Copa Sul-Americana de 2024
8,9,Cuiabá,48,35,13,9,13,36,35,+1,Fase de grupos da Copa Sul-Americana de 2024
9,10,São Paulo (Q),47,35,12,11,12,37,36,+1,Fase de grupos da Copa Libertadores de 2024[b]
10,11,Internacional,46,35,12,10,13,39,43,−4,Fase de grupos da Copa Sul-Americana de 2024
11,12,Fortaleza,45,35,12,9,14,40,42,−2,Fase de grupos da Copa Sul-Americana de 2024
12,13,Cruzeiro,44,35,11,11,13,33,30,+3,Fase de grupos da Copa Sul-Americana de 2024
13,14,Corinthians,44,35,10,14,11,40,44,−4,Fase de grupos da Copa Sul-Americana de 2024
14,15,Santos,43,35,11,10,14,38,56,−18,NaN
15,16,Vasco da Gama,42,35,11,9,15,37,45,−8,NaN
16,17,Bahia,41,35,11,8,16,44,48,−4,Rebaixados à Série B de 2024
17,18,Goiás,35,35,8,11,16,34,50,−16,Rebaixados à Série B de 2024
18,19,Coritiba (R),29,35,8,5,22,40,69,−29,Rebaixados à Série B de 2024
19,20,América Mineiro (R),21,35,4,9,22,39,74,−35,Rebaixados à Série B de 2024

,Casa \ Fora,AMM,ATP,ATM,BAH,BOT,COR,CTB,CRU,CUI,...,FLU,FOR,GOI,GRE,INT,PAL,RBB,SAN,SPA,VAS
0,América Mineiro,—,2–2,1–1,NaN,1–2,2–0,0–3,0–4,1–2,...,0–3,2–1,0–1,3–4,1–2,1–4,0–2,2–0,2–1,0–1
1,Athletico Paranaense,3–2,—,1–1,2–0,1–0,1–0,3–2,3–3,2–0,...,2–2,1–1,2–0,1–2,2–1,2–2,1–1,NaN,1–1,0–0
2,Atlético Mineiro,2–2,2–1,—,1–0,1–0,0–1,1–2,0–1,1–0,...,2–0,3–1,2–1,3–0,2–0,1–1,1–1,2–0,NaN,1–2
3,Bahia,3–1,1–1,NaN,—,1–2,0–0,3–1,2–2,0–3,...,1–0,2–0,1–1,1–2,1–0,1–0,4–0,1–2,NaN,1–1
4,Botafogo,2–0,1–1,2–0,3–0,—,3–0,4–1,NaN,0–1,...,1–0,2–0,1–1,3–4,3–1,3–4,2–0,1–1,2–1,2–0
5,Corinthians,1–1,1–0,1–1,1–5,1–0,—,3–1,2–1,1–1,...,2–0,1–1,1–1,4–4,a,0–0,0–1,1–1,1–1,3–1
6,Coritiba,3–1,2–0,1–2,2–4,NaN,NaN,—,1–0,0–3,...,2–0,0–3,0–1,1–2,0–1,0–2,0–1,0–0,1–1,0–0
7,Cruzeiro,1–1,NaN,0–1,3–0,0–0,1–1,0–0,—,0–1,...,0–2,0–1,0–1,1–0,1–2,a,0–0,2–1,1–0,2–2
8,Cuiabá,2–2,NaN,0–4,1–1,0–1,0–1,1–1,0–0,—,...,3–0,2–1,1–1,1–2,NaN,0–2,1–1,3–0,2–1,0–2
9,Flamengo,1–1,0–3,a,1–0,2–3,1–0,3–0,1–1,NaN,...,1–1,2–0,2–0,3–0,0–0,3–0,1–0,1–2,1–1,1–0
10,Fluminense,3–1,2–0,1–1,2–1,0–2,3–3,2–1,1–0,2–0,...,—,1–0,5–3,a,2–0,2–1,2–1,1–0,1–0,1–1
11,Fortaleza,3–2,1–0,2–1,0–0,2–2,2–1,3–1,0–1,0–1,...,4–2,—,NaN,1–1,1–1,2–2,0–3,4–0,0–0,2–0
12,Goiás,NaN,1–1,0–0,4–6,2–1,3–1,1–2,0–1,0–1,...,2–2,1–0,—,1–1,0–0,0–5,0–2,0–1,2–0,1–1
13,Grêmio,3–1,1–2,1–0,1–0,0–2,0–1,5–1,3–0,2–0,...,2–1,0–0,NaN,—,3–1,1–0,3–3,1–0,2–1,NaN
14,Internacional,1–1,0–2,0–2,2–0,NaN,2–2,3–4,0–0,1–2,...,0–0,0–1,1–0,3–2,—,0–0,1–0,7–1,2–1,2–1
15,Palmeiras,NaN,1–0,0–2,1–0,0–1,2–1,3–1,1–0,2–1,...,a,3–1,1–0,4–1,3–0,—,1–1,1–2,5–0,1–0
16,Red Bull Bragantino,2–2,2–0,1–2,2–1,2–2,1–0,NaN,0–3,2–0,...,1–0,NaN,2–0,2–0,0–0,2–1,—,2–0,0–0,1–1
17,Santos,3–2,1–1,0–0,3–0,2–2,0–2,2–1,0–3,0–0,...,a,NaN,4–3,2–1,1–1,0–0,1–3,—,0–0,4–1
18,São Paulo,3–0,2–1,0–2,0–0,0–0,2–1,2–1,1–0,0–0,...,1–0,1–2,2–1,3–0,2–0,0–2,1–0,4–1,—,4–2
19,Vasco da Gama,2–1,0–2,1–0,0–1,1–0,a,5–1,0–1,1–0,...,4–2,1–0,0–1,1–0,1–2,2–2,NaN,0–1,0–0,—

In [115]:
nomes_times = list(tabela_jogos["Casa \ Fora"])
apelidos = list(tabela_jogos.columns)
apelidos.pop(0)
print(nomes_times)
print(apelidos)

de_para_times = dict(zip(apelidos, nomes_times))

['América Mineiro', 'Athletico Paranaense', 'Atlético Mineiro', 'Bahia', 'Botafogo', 'Corinthians', 'Coritiba', 'Cruzeiro', 'Cuiabá', 'Flamengo', 'Fluminense', 'Fortaleza', 'Goiás', 'Grêmio', 'Internacional', 'Palmeiras', 'Red Bull Bragantino', 'Santos', 'São Paulo', 'Vasco da Gama']
['AMM', 'ATP', 'ATM', 'BAH', 'BOT', 'COR', 'CTB', 'CRU', 'CUI', 'FLA', 'FLU', 'FOR', 'GOI', 'GRE', 'INT', 'PAL', 'RBB', 'SAN', 'SPA', 'VAS']

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
C:\Users\berna\AppData\Local\Temp\ipykernel_17856\428632283.py:1: SyntaxWarning: invalid escape sequence '\ '
  nomes_times = list(tabela_jogos["Casa \ Fora"])

In [116]:
tabela_jogos_ajustada = tabela_jogos.set_index("Casa \ Fora")
tabela_jogos_ajustada = tabela_jogos_ajustada.unstack().reset_index()
tabela_jogos_ajustada = tabela_jogos_ajustada.rename(columns={"level_0": "fora", "Casa \ Fora": "casa", 0: "resultado"})

def ajustar_apelido_time(linha):
    apelido = linha["fora"]
    nome = de_para_times[apelido]
    return nome

tabela_jogos_ajustada["fora"] = tabela_jogos_ajustada.apply(ajustar_apelido_time, axis=1)
tabela_jogos_ajustada = tabela_jogos_ajustada[tabela_jogos_ajustada["fora"]!=tabela_jogos_ajustada["casa"]]

display(tabela_jogos_ajustada)

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:3: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:3: SyntaxWarning: invalid escape sequence '\ '
C:\Users\berna\AppData\Local\Temp\ipykernel_17856\493675068.py:1: SyntaxWarning: invalid escape sequence '\ '
  tabela_jogos_ajustada = tabela_jogos.set_index("Casa \ Fora")
C:\Users\berna\AppData\Local\Temp\ipykernel_17856\493675068.py:3: SyntaxWarning: invalid escape sequence '\ '
  tabela_jogos_ajustada = tabela_jogos_ajustada.rename(columns={"level_0": "fora", "Casa \ Fora": "casa", 0: "resultado"})

                fora                  casa resultado
1    América Mineiro  Athletico Paranaense       3–2
2    América Mineiro      Atlético Mineiro       2–2
3    América Mineiro                 Bahia       3–1
4    América Mineiro              Botafogo       2–0
5    América Mineiro           Corinthians       1–1
..               ...                   ...       ...
394    Vasco da Gama         Internacional       2–1
395    Vasco da Gama             Palmeiras       1–0
396    Vasco da Gama   Red Bull Bragantino       1–1
397    Vasco da Gama                Santos       4–1
398    Vasco da Gama             São Paulo       4–2

[380 rows x 3 columns]

In [117]:
tabela_jogos_ajustada["resultado"] = tabela_jogos_ajustada["resultado"].fillna("a jogar")

tabela_jogos_realizados = tabela_jogos_ajustada[tabela_jogos_ajustada["resultado"].str.contains("–")]
display(tabela_jogos_realizados)
tabela_jogos_faltantes = tabela_jogos_ajustada[~tabela_jogos_ajustada["resultado"].str.contains("–")]
tabela_jogos_faltantes = tabela_jogos_faltantes.drop(columns=["resultado"])
display(tabela_jogos_faltantes)

                fora                  casa resultado
1    América Mineiro  Athletico Paranaense       3–2
2    América Mineiro      Atlético Mineiro       2–2
3    América Mineiro                 Bahia       3–1
4    América Mineiro              Botafogo       2–0
5    América Mineiro           Corinthians       1–1
..               ...                   ...       ...
394    Vasco da Gama         Internacional       2–1
395    Vasco da Gama             Palmeiras       1–0
396    Vasco da Gama   Red Bull Bragantino       1–1
397    Vasco da Gama                Santos       4–1
398    Vasco da Gama             São Paulo       4–2

[350 rows x 3 columns]

                     fora                  casa
12        América Mineiro                 Goiás
15        América Mineiro             Palmeiras
27   Athletico Paranaense              Cruzeiro
28   Athletico Paranaense                Cuiabá
43       Atlético Mineiro                 Bahia
49       Atlético Mineiro              Flamengo
60                  Bahia       América Mineiro
86               Botafogo              Coritiba
94               Botafogo         Internacional
106           Corinthians              Coritiba
119           Corinthians         Vasco da Gama
136              Coritiba   Red Bull Bragantino
144              Cruzeiro              Botafogo
169                Cuiabá              Flamengo
198              Flamengo             São Paulo
215            Fluminense             Palmeiras
217            Fluminense                Santos
236             Fortaleza   Red Bull Bragantino
237             Fortaleza                Santos
251                 Goiás             Fortaleza
253                 Goiás                Grêmio
270                Grêmio            Fluminense
285         Internacional           Corinthians
288         Internacional                Cuiabá
307             Palmeiras              Cruzeiro
339   Red Bull Bragantino         Vasco da Gama
341                Santos  Athletico Paranaense
362             São Paulo      Atlético Mineiro
363             São Paulo                 Bahia
393         Vasco da Gama                Grêmio

In [118]:
tabela_jogos_realizados[["gols_casa", "gols_fora"]] = tabela_jogos_realizados["resultado"].str.split("–", expand=True)
tabela_jogos_realizados = tabela_jogos_realizados.drop(columns=["resultado"])
tabela_jogos_realizados["gols_casa"] = tabela_jogos_realizados["gols_casa"].astype(int)
tabela_jogos_realizados["gols_fora"] = tabela_jogos_realizados["gols_fora"].astype(int)

display(tabela_jogos_realizados)

C:\Users\berna\AppData\Local\Temp\ipykernel_17856\743578657.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_jogos_realizados[["gols_casa", "gols_fora"]] = tabela_jogos_realizados["resultado"].str.split("–", expand=True)
C:\Users\berna\AppData\Local\Temp\ipykernel_17856\743578657.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_jogos_realizados[["gols_casa", "gols_fora"]] = tabela_jogos_realizados["resultado"].str.split("–", expand=True)

                fora                  casa  gols_casa  gols_fora
1    América Mineiro  Athletico Paranaense          3          2
2    América Mineiro      Atlético Mineiro          2          2
3    América Mineiro                 Bahia          3          1
4    América Mineiro              Botafogo          2          0
5    América Mineiro           Corinthians          1          1
..               ...                   ...        ...        ...
394    Vasco da Gama         Internacional          2          1
395    Vasco da Gama             Palmeiras          1          0
396    Vasco da Gama   Red Bull Bragantino          1          1
397    Vasco da Gama                Santos          4          1
398    Vasco da Gama             São Paulo          4          2

[350 rows x 4 columns]

In [119]:
media_gols_casa = tabela_jogos_realizados.groupby("casa").mean(numeric_only=True)
media_gols_casa = media_gols_casa.rename(columns={"gols_casa": "gols_feitos_casa", "gols_fora": "gols_sofridos_casa"})
display(media_gols_casa)
media_gols_fora = tabela_jogos_realizados.groupby("fora").mean(numeric_only=True)
media_gols_fora = media_gols_fora.rename(columns={"gols_casa": "gols_sofridos_fora", "gols_fora": "gols_feitos_fora"})
display(media_gols_fora)

                      gols_feitos_casa  gols_sofridos_casa
casa
América Mineiro               1.000000            2.000000
Athletico Paranaense          1.666667            1.055556
Atlético Mineiro              1.444444            0.833333
Bahia                         1.470588            1.117647
Botafogo                      2.000000            0.944444
Corinthians                   1.388889            1.166667
Coritiba                      0.882353            1.411765
Cruzeiro                      0.705882            0.882353
Cuiabá                        1.176471            1.176471
Flamengo                      1.411765            0.705882
Fluminense                    1.722222            0.833333
Fortaleza                     1.500000            1.111111
Goiás                         1.000000            1.388889
Grêmio                        1.823529            0.882353
Internacional                 1.500000            1.111111
Palmeiras                     1.764706            0.705882
Red Bull Bragantino           1.529412            0.705882
Santos                        1.470588            1.352941
São Paulo                     1.555556            0.722222
Vasco da Gama                 1.176471            1.058824

                      gols_sofridos_fora  gols_feitos_fora
fora
América Mineiro                 2.235294          1.235294
Athletico Paranaense            1.176471          1.000000
Atlético Mineiro                0.705882          1.176471
Bahia                           1.611111          1.055556
Botafogo                        0.941176          1.176471
Corinthians                     1.352941          0.882353
Coritiba                        2.444444          1.333333
Cruzeiro                        0.833333          1.166667
Cuiabá                          0.833333          0.888889
Flamengo                        1.388889          1.666667
Fluminense                      1.647059          0.882353
Fortaleza                       1.294118          0.764706
Goiás                           1.470588          0.941176
Grêmio                          2.111111          1.444444
Internacional                   1.352941          0.705882
Palmeiras                       1.111111          1.555556
Red Bull Bragantino             1.055556          1.111111
Santos                          1.833333          0.722222
São Paulo                       1.352941          0.529412
Vasco da Gama                   1.444444          0.888889

In [120]:
tabela_estatisticas = media_gols_casa.merge(media_gols_fora, left_index=True, right_index=True)
tabela_estatisticas = tabela_estatisticas.reset_index()
tabela_estatisticas = tabela_estatisticas.rename(columns={"casa" : "time"})
display(tabela_estatisticas)

,time,gols_feitos_casa,gols_sofridos_casa,gols_sofridos_fora,gols_feitos_fora
0,América Mineiro,1.000000,2.000000,2.235294,1.235294
1,Athletico Paranaense,1.666667,1.055556,1.176471,1.000000
2,Atlético Mineiro,1.444444,0.833333,0.705882,1.176471
3,Bahia,1.470588,1.117647,1.611111,1.055556
4,Botafogo,2.000000,0.944444,0.941176,1.176471
5,Corinthians,1.388889,1.166667,1.352941,0.882353
6,Coritiba,0.882353,1.411765,2.444444,1.333333
7,Cruzeiro,0.705882,0.882353,0.833333,1.166667
8,Cuiabá,1.176471,1.176471,0.833333,0.888889
9,Flamengo,1.411765,0.705882,1.388889,1.666667
10,Fluminense,1.722222,0.833333,1.647059,0.882353
11,Fortaleza,1.500000,1.111111,1.294118,0.764706
12,Goiás,1.000000,1.388889,1.470588,0.941176
13,Grêmio,1.823529,0.882353,2.111111,1.444444
14,Internacional,1.500000,1.111111,1.352941,0.705882
15,Palmeiras,1.764706,0.705882,1.111111,1.555556
16,Red Bull Bragantino,1.529412,0.705882,1.055556,1.111111
17,Santos,1.470588,1.352941,1.833333,0.722222
18,São Paulo,1.555556,0.722222,1.352941,0.529412
19,Vasco da Gama,1.176471,1.058824,1.444444,0.888889

In [121]:
from scipy.stats import poisson 

def calcular_pontuacao_esperada(linha):
    time_casa = linha["casa"]
    time_fora = linha["fora"]

    lamba_casa = (tabela_estatisticas.loc[tabela_estatisticas["time"]==time_casa, "gols_feitos_casa"].iloc[0] 
                  * tabela_estatisticas.loc[tabela_estatisticas["time"]==time_fora, "gols_sofridos_fora"].iloc[0])
    
    lamba_fora = (tabela_estatisticas.loc[tabela_estatisticas["time"]==time_fora, "gols_feitos_fora"].iloc[0] 
                  * tabela_estatisticas.loc[tabela_estatisticas["time"]==time_casa, "gols_sofridos_casa"].iloc[0])
    
    pv_casa = 0
    p_empate = 0
    pv_fora = 0

    for gols_casa in range(8):
        for gols_fora in range(8):
            probabilidade_resultado = poisson.pmf(gols_casa, lamba_casa) * poisson.pmf(gols_fora, lamba_fora)
            if gols_casa == gols_fora:
                p_empate += probabilidade_resultado
            elif gols_casa > gols_fora:
                pv_casa += probabilidade_resultado
            elif gols_casa < gols_fora:
                pv_fora += probabilidade_resultado

    
    ve_casa = pv_casa * 3 + p_empate
    ve_fora = pv_fora * 3 + p_empate
    linha["pontos_casa"] = ve_casa
    linha["pontos_fora"] = ve_fora
    return(linha)

In [122]:
tabela_jogos_faltantes = tabela_jogos_faltantes.apply(calcular_pontuacao_esperada, axis=1)
display(tabela_jogos_faltantes)

                     fora                  casa  pontos_casa  pontos_fora
12        América Mineiro                 Goiás     1.692060     1.097839
15        América Mineiro             Palmeiras     2.595239     0.189743
27   Athletico Paranaense              Cruzeiro     1.287204     1.373984
28   Athletico Paranaense                Cuiabá     1.514050     1.221000
43       Atlético Mineiro                 Bahia     1.159271     1.563992
49       Atlético Mineiro              Flamengo     1.473014     1.202679
60                  Bahia       América Mineiro     1.097977     1.687359
86               Botafogo              Coritiba     0.801446     1.954581
94               Botafogo         Internacional     1.443337     1.299396
106           Corinthians              Coritiba     1.325465     1.400426
119           Corinthians         Vasco da Gama     1.832944     0.915119
136              Coritiba   Red Bull Bragantino     2.564684     0.239341
144              Cruzeiro              Botafogo     1.758629     0.997249
169                Cuiabá              Flamengo     1.787451     0.901900
198              Flamengo             São Paulo     1.973233     0.818363
215            Fluminense             Palmeiras     2.588109     0.270013
217            Fluminense                Santos     2.105466     0.701259
236             Fortaleza   Red Bull Bragantino     2.339365     0.465070
237             Fortaleza                Santos     1.948382     0.827771
251                 Goiás             Fortaleza     2.099170     0.699960
253                 Goiás                Grêmio     2.420174     0.416899
270                Grêmio            Fluminense     2.450263     0.347750
285         Internacional           Corinthians     2.085140     0.694137
288         Internacional                Cuiabá     1.911553     0.836720
307             Palmeiras              Cruzeiro     0.920332     1.801350
339   Red Bull Bragantino         Vasco da Gama     1.409655     1.314908
341                Santos  Athletico Paranaense     2.550991     0.297638
362             São Paulo      Atlético Mineiro     2.399279     0.409521
363             São Paulo                 Bahia     2.307037     0.495102
393         Vasco da Gama                Grêmio     2.431319     0.406856

In [123]:
def ajustar_nome_time(linha):
    for name in nomes_times:
        if name in linha ["Equipevde"]:
            return name

tabela_classificacao["time"] = tabela_classificacao.apply(ajustar_nome_time,axis=1)
tabela_classificacao_atualizada = tabela_classificacao[["time", "Pts"]]
tabela_classificacao_atualizada["Pts"].astype(int)


display(tabela_classificacao_atualizada)

                    time  Pts
0              Palmeiras   63
1               Flamengo   63
2               Botafogo   62
3       Atlético Mineiro   60
4                 Grêmio   59
5    Red Bull Bragantino   59
6             Fluminense   53
7   Athletico Paranaense   52
8                 Cuiabá   48
9              São Paulo   47
10         Internacional   46
11             Fortaleza   45
12              Cruzeiro   44
13           Corinthians   44
14                Santos   43
15         Vasco da Gama   42
16                 Bahia   41
17                 Goiás   35
18              Coritiba   29
19       América Mineiro   21

In [124]:
tabela_pontuacao_casa = tabela_jogos_faltantes.groupby("casa").sum(numeric_only=True)[["pontos_casa"]]
tabela_pontuacao_fora = tabela_jogos_faltantes.groupby("fora").sum(numeric_only=True)

display(tabela_pontuacao_casa)
display(tabela_pontuacao_fora)

                      pontos_casa
casa
América Mineiro          1.097977
Athletico Paranaense     2.550991
Atlético Mineiro         2.399279
Bahia                    3.466307
Botafogo                 1.758629
Corinthians              2.085140
Coritiba                 2.126911
Cruzeiro                 2.207535
Cuiabá                   3.425603
Flamengo                 3.260465
Fluminense               2.450263
Fortaleza                2.099170
Goiás                    1.692060
Grêmio                   4.851493
Internacional            1.443337
Palmeiras                5.183348
Red Bull Bragantino      4.904050
Santos                   4.053847
São Paulo                1.973233
Vasco da Gama            3.242599

                      pontos_casa  pontos_fora
fora
América Mineiro          4.287298     1.287582
Athletico Paranaense     2.801254     2.594983
Atlético Mineiro         2.632284     2.766670
Bahia                    1.097977     1.687359
Botafogo                 2.244783     3.253977
Corinthians              3.158409     2.315545
Coritiba                 2.564684     0.239341
Cruzeiro                 1.758629     0.997249
Cuiabá                   1.787451     0.901900
Flamengo                 1.973233     0.818363
Fluminense               4.693575     0.971272
Fortaleza                4.287747     1.292841
Goiás                    4.519344     1.116859
Grêmio                   2.450263     0.347750
Internacional            3.996692     1.530857
Palmeiras                0.920332     1.801350
Red Bull Bragantino      1.409655     1.314908
Santos                   2.550991     0.297638
São Paulo                4.706316     0.904623
Vasco da Gama            2.431319     0.406856

In [125]:
def atualizar_pontuacao_previsao(linha):
    time = linha["time"]
    pontuacao = int(linha["Pts"]) + float (tabela_pontuacao_casa.loc[time, "pontos_casa"]) + float (tabela_pontuacao_fora.loc[time, "pontos_fora"])
    return pontuacao

tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada.apply(atualizar_pontuacao_previsao, axis=1)
tabela_classificacao_atualizada = tabela_classificacao_atualizada.sort_values(by="Pts", ascending=False)
tabela_classificacao_atualizada = tabela_classificacao_atualizada.reset_index(drop=True)
tabela_classificacao_atualizada.index = tabela_classificacao_atualizada.index + 1
display(tabela_classificacao_atualizada)

C:\Users\berna\AppData\Local\Temp\ipykernel_17856\3922508583.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada.apply(atualizar_pontuacao_previsao, axis=1)

                    time        Pts
1              Palmeiras  69.984698
2               Flamengo  67.078828
3               Botafogo  67.012606
4    Red Bull Bragantino  65.218958
5       Atlético Mineiro  65.165949
6                 Grêmio  64.199243
7   Athletico Paranaense  57.145975
8             Fluminense  56.421535
9                 Cuiabá  52.327502
10             São Paulo  49.877856
11         Internacional  48.974194
12           Corinthians  48.400685
13             Fortaleza  48.392010
14                Santos  47.351485
15              Cruzeiro  47.204784
16                 Bahia  46.153666
17         Vasco da Gama  45.649454
18                 Goiás  37.808919
19              Coritiba  31.366251
20       América Mineiro  23.385559